### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by adamshand** [AdrianGonz97/pocketbase-sveltekit-demo#1]
As a newish JS/Svelte developer, wrapping my head around how OAuth is supposed to work was hard.  

This was the only example was the only one I found which was complete enough to actually work, yet still simple enough to understand.

Thank you!

Best wishes from New Zealand,
Adam.

**Comment by AdrianGonz97** [comment]
I'm very happy to hear that! Thanks for reaching out! 😄
